name: TawariApp-Debugger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'  # غيرناها من 11 إلى 17
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'  # غيرناها لأحدث إصدار
        
    - name: Enable Flutter Web
      run: flutter config --enable-web
      
    - name: Install dependencies
      run: flutter pub get
      
    - name: Clean build
      run: flutter clean
      
    - name: Build APK
      run: flutter build apk --debug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: TawariApp-Debugger
        path: build/app/outputs/flutter-apk/app-debug.apk
